# Generated by Django 2.2.2 on 2019-08-12 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_name', models.CharField(max_length=30)),
                ('consignment_type', models.CharField(choices=[('LETR', 'Letter')], max_length=30)),
                ('consignment_weight_in_gm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consignment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consignment_source', models.CharField(choices=[(481001, 'Balaghat')], max_length=30)),
                ('consignment_destination', models.CharField(choices=[(481001, 'Balaghat')], max_length=30)),
                ('consignment_address', models.TextField(max_length=150)),
                ('consignment_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
