# Generated by Django 2.2.2 on 2019-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_auto_20190812_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignment_destination_pin_code',
            field=models.IntegerField(choices=[(481001, 'Balaghat (BGT)')], default=481001),
        ),
    ]
