# Generated by Django 2.2.2 on 2019-08-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consignment', '0005_auto_20190812_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_code',
            field=models.CharField(default='BAQ', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(default='Basoda', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_pincode',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_name', models.CharField(max_length=30)),
                ('material', models.CharField(choices=[('Letter', 'Letter')], max_length=30)),
                ('package_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=30)),
                ('service_type', models.CharField(choices=[('Premium', 'Premium'), ('Overnight', 'Overnight'), ('Regular', 'Regular')], max_length=30)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_in_gm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consignment_address', models.TextField(max_length=150)),
                ('consignment_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consig', to='consignment.Office')),
                ('consignment_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consignment_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='consignment.Office')),
            ],
        ),
    ]
