# Generated by Django 2.2.2 on 2019-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0006_auto_20190812_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
