# Generated by Django 2.2.2 on 2019-08-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0007_auto_20190812_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignment_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='consignment.Office'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='consignment_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='consignment.Office'),
        ),
    ]
