# Generated by Django 2.2.2 on 2019-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0008_auto_20190812_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_address',
            field=models.TextField(default='enter the address', max_length=150),
            preserve_default=False,
        ),
    ]
