# Generated by Django 2.2.2 on 2019-08-12 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0009_office_office_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('RECIEVED', 'Recieved'), ('DISPATCHED', 'Dispatched')], max_length=30)),
                ('transporter', models.CharField(choices=[('RECIEVED', 'Recieved'), ('DISPATCHED', 'Dispatched')], max_length=30)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignment.Consignment')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hub', to='consignment.Office')),
            ],
        ),
    ]
