# Generated by Django 2.2.2 on 2019-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0011_auto_20190812_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporter',
            name='phone_no',
            field=models.CharField(default=10000034, max_length=30),
            preserve_default=False,
        ),
    ]
