# Generated by Django 2.2.2 on 2019-08-12 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='aadhar_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
