# Generated by Django 2.2.2 on 2019-08-12 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20190812_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtended',
            new_name='Profile',
        ),
    ]
